In [11]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
Vect=CountVectorizer(binary=True)
Corpus=["Tessearct is an optical recogonition engine","optical character"]
Vect.fit(Corpus)
print(Vect.transform(["Tessearct is an optical character recognition engine"]).toarray())

[[1 1 1 1 1 0 1]]


In [16]:
Vect=CountVectorizer(binary=False)
Corpus=["Tessearct is an optical recogonition engine","optical character"]
Vect.fit(Corpus)
print(Vect.transform(["Tessearct is an optical character recognition engine"]).toarray())

[[1 1 1 1 1 0 1]]


In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
similarity=cosine_similarity(Vect.transform(["""Summer is a charming flirt. Easy going and casual. Summer doesnt huff and puff to win our affection. It has us at "Hello". Winter broods like the tortured protagonist of big fat russian novel. It is daunting and dramatic, burning with a slow intensity.The seasons reputation precedes itself, and often, not in a good way. It has a way of whittling down everything to its bare bones. Even relationships not attuned to its ebbs and flows can fray. At a dinner conversation I once attended, I listened in bemusement as a recent divorcee, made the case that it was the Scandinavian frost that had cooled his exwifes ardour. How original"""]).toarray())
Vect.transform([""""One of the finer books i read this year was John Kaag's Hiking With Nietzsche, in which Kaag, a professor of philosophy, rekindles his passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland. It's a near-precise rendering of the travelogue as a self-help book. A young Kaag was an avowed Nietzsche acolyte but given the ravages of responsibilities and adulthood, the writer put his affinity to test by undertaking physically enduring hikes through the Alps, revisiting haunts that the philosopher escaped to, in search of solitude and salve. The journey's demands, coupled with his own innre turmoil, are catnip for anybody feeling at cross purposes with their own life."""]).toarray()


array([[1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [14]:
print(similarity)

[[1.]]


In [16]:
str1=""""Summer is a charming flirt. Easy going and casual. Summer doesnt huff and puff to win our affection. It has us at "Hello". Winter broods like the tortured protagonist of big fat russian novel. It is daunting and dramatic, burning with a slow intensity.The seasons reputation precedes itself, and often, not in a good way. It has a way of whittling down everything to its bare bones. Even relationships not attuned to its ebbs and flows can fray. At a dinner conversation I once attended, I listened in bemusement as a recent divorcee, made the case that it was the Scandinavian frost that had cooled his exwifes ardour. How original"""
str2="One of the finer books i read this year was John Kaag's Hiking With Nietzsche, in which Kaag, a professor of philosophy, rekindles his passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland. It's a near-precise rendering of the travelogue as a self-help book. A young Kaag was an avowed Nietzsche acolyte but given the ravages of responsibilities and adulthood, the writer put his affinity to test by undertaking physically enduring hikes through the Alps, revisiting haunts that the philosopher escaped to, in search of solitude and salve. The journey's demands, coupled with his own innre turmoil, are catnip for anybody feeling at cross purposes with their own life."


In [17]:
Vect=TfidfVectorizer(binary=True)
Corpus=["Tessearct is an optical recogonition engine","optical character"]
Vect.fit(Corpus)
print(Vect.transform(["Tessearct is an optical character recognition engine"]).toarray())

[[0.4261596  0.4261596  0.4261596  0.4261596  0.30321606 0.
  0.4261596 ]]


In [18]:
Vect=TfidfVectorizer(binary=True)
Corpus=[str1,str2]
Vect.fit(Corpus)
vecstr1=Vect.transform([str1]).toarray()
vecstr2=Vect.transform([str2]).toarray()

In [19]:
sim=cosine_similarity(vecstr1,vecstr2)

In [20]:
sim

array([[0.07934834]])

In [21]:
print('Cosine similarity between text 1 and text 2',cosine_similarity(vecstr1,vecstr2))

Cosine similarity between text 1 and text 2 [[0.07934834]]
